<<<<<<< HEAD
<<<<<<< HEAD
---
title: "Untitled"
output: md_document
date: "2024-10-25"
---

# Teammitglieder 
* Kirachen 
* Beckers 
* Konar
* Momot
* Aksoy

# Forschungsfrage
# Faktorenraum
=======
<<<<<<< HEAD
<<<<<<< HEAD
---
title: "Untitled"
author: "Zehra"
output: md_document
date: "2024-10-21"
---

# Teammitglieder
* Emilia
* Monique 
* Zehra
* Elcin 


# Forschungsfrage



# Faktorenraum
Hier wird später ein Bild eingebunden.

=======
---
title: "Untitled"
output: md_document
date: "2024-10-25"
---

# Teammitglieder 
* Kirachen 
* Beckers 
* Konar
* Momot
* Aksoy




# Faktorenraum
>>>>>>> 02aa74d9cc9c45c9a78f11b553b51ae203cdf317
=======
---
title: "Untitled"
output: md_document
date: "2024-10-25"
---

# Teammitglieder 
* Beckers 
* Konar
* Momot
* Aksoy


# Forschungsfrage
Welche Faktoren beeinflussen die Akzeptanz und die Privatsphären-Wahrnehmung bei der Nutzung eines KI-Chatbots in der Kommunalverwaltung zur Unterstützung bei Formularprozessen am Beispiel der Sperrmüllanmeldung?

# Faktorenraum
>>>>>>> 7c8f9ef694b46c022a596c27d842d7b30e0bfca5
>>>>>>> 5ef91bcadd6d8de5001cd02aa9ca38e740fa17b4
=======

# Teammitglieder

-   Emilia
-   Monique
-   Zehra
-   Elcin 

# Forschungsfrage

Welche Faktoren beeinflussen die Akzeptanz und die
Privatsphären-Wahrnehmung bei der Nutzung eines KI-Chatbots in der
Kommunalverwaltung zur Unterstützung bei Formularprozessen am Beispiel
der Sperrmüllanmeldung?

# Faktorenraum
Readme_files/Faktorenraum.jpeg

# Operationalisierung
>>>>>>> b9f64acad2586f4079b0235368fee9ca52422b62
